name: Build-push base image

on:
  push:
    paths:
      - Dockerfile.base
      - requirements.txt

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: build image
      run: docker build -t quay.io/sustainable_computing_io/kepler-estimator-base:latest . -f Dockerfile.base
      
    - name: Login to Quay
      if: ${{ github.repository_owner == 'sustainable-computing-io' }}
      uses: docker/login-action@v1
      with:
          registry: quay.io/sustainable_computing_io
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_TOKEN }}

    - name: push to quay
      if: ${{ github.repository_owner == 'sustainable-computing-io' }}
      run: docker push quay.io/sustainable_computing_io/kepler-estimator-base:latest

    - name: Login to ghcr
      if: ${{ github.repository_owner != 'sustainable-computing-io' }}
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}

    - name: push to ghcr
      run: |
        docker tag quay.io/sustainable_computing_io/kepler-estimator-base:latest ghcr.io/${{ github.repository_owner }}/kepler-estimator-base:latest \
        && docker push ghcr.io/${{ github.repository_owner }}/kepler-estimator-base:latest

