name: Build-push base image

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile.base
      - requirements.txt

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: podman build -t quay.io/sustainable_computing_io/kepler-estimator-base:latest -f Dockerfile.base

    - name: Login to Quay
      if: ${{ github.repository_owner == 'sustainable-computing-io' }}
      uses: docker/login-action@v1
      with:
          registry: quay.io/sustainable_computing_io
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_TOKEN }}

    - name: Push to quay
      if: ${{ github.repository_owner == 'sustainable-computing-io' }}
      run: podman push quay.io/sustainable_computing_io/kepler-estimator-base:latest