name: Build Push

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: build image
      run: docker build -t quay.io/sustainable_computing_io/kepler_estimator:latest .
      
    - name: Login to Quay
      if: ${{ github.repository_owner == 'sustainable-computing-io' }}
      uses: docker/login-action@v1
      with:
          registry: quay.io/sustainable_computing_io
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_TOKEN }}      

    - name: push to quay
      if: ${{ github.repository_owner == 'sustainable-computing-io' }}
      run: docker push quay.io/sustainable_computing_io/kepler_estimator:latest
