name: Integration Test

on:
  push:
    branches: [ dev ] # to be removed

jobs:
  cluster-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Kind with kepler-model-server
        uses: sustainable-computing-io/kepler-model-server/.github/workflows/cluster_deploy.yml
        with:
          load_initial_models: true
          image-build: false
      
      - uses: actions/checkout@v3

      - name: Build images
        run: |
          docker build -t kind-registry:5000/kepler_estimator:latest server/ -f server/dockerfiles/Dockerfile
          docker tag kind-registry:5000/kepler_estimator:latest quay.io/sustainable_computing_io/kepler_estimator:latest

      - name: Deploy test jobs
        run: kubectl create -f deploy/test-jobs.yaml

      - name: Check job done without error
        run: kubectl wait --for=condition=complete --timeout=30s job/estimator-job